import React from 'react';

const PrivacyPolicy: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8">
      <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
      <p className="mb-4"><strong>Last updated:</strong> [DATE]</p>

      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure 
        of Your information when You use the Service and tells You about Your privacy rights and how 
        the law protects You.
      </p>

      <p className="mb-4">
        We use Your Personal data to provide and improve the Service. By using the Service, You agree 
        to the collection and use of information in accordance with this Privacy Policy.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Interpretation and Definitions</h2>
      
      <h3 className="text-xl font-semibold mt-4 mb-2">Interpretation</h3>
      <p className="mb-4">
        The words of which the initial letter is capitalized have meanings defined under the following 
        conditions. The following definitions shall have the same meaning regardless of whether they 
        appear in singular or in plural.
      </p>
      
      <h3 className="text-xl font-semibold mt-4 mb-2">Definitions</h3>
      <p className="mb-2"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
      <p className="mb-2"><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to [COMPANY NAME], [ADDRESS].</p>
      <p className="mb-2"><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</p>
      <p className="mb-2"><strong>Country</strong> refers to: [COUNTRY]</p>
      <p className="mb-2"><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</p>
      <p className="mb-2"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
      <p className="mb-2"><strong>Service</strong> refers to the Website.</p>
      <p className="mb-2"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
      <p className="mb-2"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
      <p className="mb-2"><strong>Website</strong> refers to [WEBSITE NAME], accessible from [WEBSITE URL]</p>
      <p className="mb-4"><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Collecting and Using Your Personal Data</h2>
      
      <h3 className="text-xl font-semibold mt-4 mb-2">Types of Data Collected</h3>
      
      <h4 className="text-lg font-semibold mt-3 mb-2">Personal Data</h4>
      <p className="mb-4">
        While using Our Service, We may ask You to provide Us with certain personally identifiable 
        information that can be used to contact or identify You. Personally identifiable information 
        may include, but is not limited to:
      </p>
      <ul className="list-disc pl-6 mb-4">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Address, State, Province, ZIP/Postal code, City</li>
        <li>Usage Data</li>
      </ul>
      
      <h4 className="text-lg font-semibold mt-3 mb-2">Usage Data</h4>
      <p className="mb-4">
        Usage Data is collected automatically when using the Service.
      </p>
      <p className="mb-4">
        Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), 
        browser type, browser version, the pages of our Service that You visit, the time and date of Your 
        visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You 
        access the Service by or through a mobile device, We may collect certain information automatically, 
        including, but not limited to, the type of mobile device You use, Your mobile device unique ID, 
        the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet 
        browser You use, unique device identifiers and other diagnostic data.
      </p>
      
      <h4 className="text-lg font-semibold mt-3 mb-2">Tracking Technologies and Cookies</h4>
      <p className="mb-4">
        We use Cookies and similar tracking technologies to track the activity on Our Service and store 
        certain information. Tracking technologies used are beacons, tags, and scripts to collect and 
        track information and to improve and analyze Our Service.
      </p>
      <p className="mb-4">
        You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. 
        However, if You do not accept Cookies, You may not be able to use some parts of Our Service.
      </p>
      <p className="mb-2"><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</p>
      <p className="mb-2"><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and various settings.</p>
      <p className="mb-2"><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</p>
      <p className="mb-4"><strong>Advertising Cookies.</strong> Advertising Cookies are used to serve you with advertisements that may be relevant to you and your interests.</p>

      <h3 className="text-xl font-semibold mt-4 mb-2">Use of Your Personal Data</h3>
      <p className="mb-4">
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className="list-disc pl-6 mb-4">
        <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
        <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
        <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or services, including the security updates, when necessary or reasonable for their implementation.</li>
        <li><strong>To provide You with news, special offers and general information</strong> about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
        <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
        <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
        <li><strong>For other purposes</strong>: We may use Your information for data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
      </ul>

      <h3 className="text-xl font-semibold mt-4 mb-2">Retention of Your Personal Data</h3>
      <p className="mb-4">
        The Company will retain Your Personal Data only for as long as is necessary for the purposes 
        set out in this Privacy Policy. We will retain and use Your Personal Data to the extent 
        necessary to comply with our legal obligations (for example, if we are required to retain 
        your data to comply with applicable laws), resolve disputes, and enforce our legal agreements 
        and policies.
      </p>

      <h3 className="text-xl font-semibold mt-4 mb-2">Transfer of Your Personal Data</h3>
      <p className="mb-4">
        Your information, including Personal Data, is processed at the Company's operating offices 
        and in any other places where the parties involved in the processing are located. It means 
        that this information may be transferred to — and maintained on — computers located outside 
        of Your state, province, country or other governmental jurisdiction where the data protection 
        laws may differ than those from Your jurisdiction.
      </p>

      <h3 className="text-xl font-semibold mt-4 mb-2">Disclosure of Your Personal Data</h3>
      <p className="mb-2"><strong>Business Transactions:</strong> If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred.</p>
      <p className="mb-2"><strong>Law enforcement:</strong> Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
      <p className="mb-4"><strong>Other legal requirements:</strong> The Company may disclose Your Personal Data in the good faith belief that such action is necessary to comply with a legal obligation, protect and defend the rights or property of the Company, prevent or investigate possible wrongdoing in connection with the Service, protect the personal safety of Users of the Service or the public, or protect against legal liability.</p>

      <h3 className="text-xl font-semibold mt-4 mb-2">Security of Your Personal Data</h3>
      <p className="mb-4">
        The security of Your Personal Data is important to Us, but remember that no method of 
        transmission over the Internet, or method of electronic storage is 100% secure. While 
        We strive to use commercially acceptable means to protect Your Personal Data, We cannot 
        guarantee its absolute security.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Children's Privacy</h2>
      <p className="mb-4">
        Our Service does not address anyone under the age of 13. We do not knowingly collect 
        personally identifiable information from anyone under the age of 13. If You are a parent 
        or guardian and You are aware that Your child has provided Us with Personal Data, please 
        contact Us. If We become aware that We have collected Personal Data from anyone under 
        the age of 13 without verification of parental consent, We take steps to remove that 
        information from Our servers.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Links to Other Websites</h2>
      <p className="mb-4">
        Our Service may contain links to other websites that are not operated by Us. If You click 
        on a third party link, You will be directed to that third party's site. We strongly advise 
        You to review the Privacy Policy of every site You visit.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Changes to this Privacy Policy</h2>
      <p className="mb-4">
        We may update Our Privacy Policy from time to time. We will notify You of any changes by 
        posting the new Privacy Policy on this page.
      </p>

      <h2 className="text-2xl font-semibold mt-6 mb-4">Contact Us</h2>
      <p className="mb-4">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="list-disc pl-6">
        <li>By email: [EMAIL ADDRESS]</li>
        <li>By visiting this page on our website: [CONTACT PAGE URL]</li>
        <li>By phone number: [PHONE NUMBER]</li>
        <li>By mail at: [MAILING ADDRESS]</li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;