import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const projectRoot = process.cwd();
const enPath = path.join(projectRoot, "app", "i18n", "en.json");
const outPath = path.join(projectRoot, "app", "i18n", "keys.ts");

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, "utf8"));
}

function isPlainObject(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function collectKeys(obj, prefix = "") {
  if (!isPlainObject(obj)) return [];
  const keys = [];
  for (const [key, value] of Object.entries(obj)) {
    const next = prefix ? `${prefix}.${key}` : key;
    if (isPlainObject(value)) keys.push(...collectKeys(value, next));
    else keys.push(next);
  }
  return keys;
}

if (!fs.existsSync(enPath)) {
  console.error(`[i18n:keys] Missing base dictionary: ${path.relative(projectRoot, enPath)}`);
  process.exit(1);
}

const enJson = readJson(enPath);
const keys = collectKeys(enJson).sort((a, b) => a.localeCompare(b));

const lines = [];
lines.push("/* eslint-disable */");
lines.push("// This file is auto-generated by `npm run i18n:keys`.");
lines.push("// Do not edit manually.");
lines.push("");
lines.push("export const I18N_KEYS = [");
for (const key of keys) lines.push(`  ${JSON.stringify(key)},`);
lines.push("] as const;");
lines.push("");
lines.push("export type I18nKey = (typeof I18N_KEYS)[number];");
lines.push("");

fs.writeFileSync(outPath, lines.join("\n"), "utf8");
console.log(`[i18n:keys] Wrote ${path.relative(projectRoot, outPath)} (${keys.length} keys).`);
